/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

/**
 * @author Daniyal (iamdaniyalz.pro@gmail.com)
 */

public class HomePage extends BaseWebPage {

    public HomePage(WebDriver driver) {
        super(driver);
    }

    @FindBy(how = How.ID, using = "txtSearch")
    private WebElement SearchBar;


    public String WebsiteAccessibility() {

        if(waitForElement(SearchBar)) {
            return "Website is Accessible";
        }

        else {
            System.out.println("Website not accessible");
        }
        return "Website not Accessible";
    }

}
