/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pages;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

/**
 * @author Daniyal (iamdaniyalz.pro@gmail.com)
 */
public class Product extends BaseWebPage {

    public Product(WebDriver driver) {
        super(driver);
    }

    @FindBy(how = How.ID, using = "txtSearch")
    private WebElement SearchBar;

    @FindBy(how = How.XPATH, using = "//img[@title='Official - Vintage Band T-Shirt Rolling Stones']")
    private WebElement ProductOne;

    @FindBy(how = How.XPATH, using = "//img[@title='Karrimor - X Lite Run Headband Mens']")
    private WebElement ProductTwo;

    @FindBy(how = How.XPATH, using = "//a[text()='Small']")
    private WebElement SizeSmall;

    @FindBy(how = How.XPATH, using = "//a[text()='One Size']")
    private WebElement OneSize;

    @FindBy(how = How.XPATH, using = "//div[@class='hidden-xs']//a[@class='addToBag']")
    private WebElement AddToBag;

    public void searchProductOne() {
        SearchBar.click();
        SearchBar.sendKeys("Band T Shirts");
        SearchBar.sendKeys(Keys.RETURN);
    }

    public void addProductOneToBag() {
        ((JavascriptExecutor)driver).executeScript("arguments[0].scrollIntoView();", ProductOne);
        ProductOne.click();
        waitForElement(SizeSmall);
        SizeSmall.click();
        AddToBag.click();
    }

    public void searchProductTwo() {
        SearchBar.click();
        SearchBar.sendKeys("Headband");
        SearchBar.sendKeys(Keys.RETURN);
    }

    public void addProductTwoToBag() {
        ((JavascriptExecutor)driver).executeScript("arguments[0].scrollIntoView();", ProductTwo);
        ProductTwo.click();
        waitForElement(OneSize);
        OneSize.click();
        AddToBag.click();
    }

}
