/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pages;

import io.cucumber.core.api.Scenario;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

/**
 * @author Daniyal (iamdaniyalz.pro@gmail.com)
 */
public class Product extends BaseWebPage {

    public Product (WebDriver driver) {
        super(driver, scenario);
    }

    @FindBy(how = How.ID, using = "txtSearch")
    private WebElement SearchBar;

    @FindBy(how = How.XPATH, using = "//img[@title='Official - Vintage Band T-Shirt Rolling Stones']")
    private WebElement ProductOne;

    @FindBy(how = How.XPATH, using = "//img[@title='Karrimor - X Lite Run Headband Mens']")
    private WebElement ProductTwo;

    @FindBy(how = How.XPATH, using = "//a[text()='Small']")
    private WebElement SizeSmall;

    @FindBy(how = How.XPATH, using = "//a[text()='One Size']")
    private WebElement OneSize;

    @FindBy(how = How.XPATH, using = "//div[@class='hidden-xs']//a[@class='addToBag']")
    private WebElement AddToBag;

    public void searchProductOne() {
        Click(SearchBar);
        SearchBar.sendKeys("Band T Shirts");
        SearchBar.sendKeys(Keys.RETURN);
    }

    public void addProductOneToBag() {
        scrollIntoView(ProductOne);
        Click(ProductOne);
        waitForElement(SizeSmall);
        Click(SizeSmall);
        Click(AddToBag);
    }

    public void searchProductTwo() {
        Click(SearchBar);
        SearchBar.sendKeys("Headband");
        SearchBar.sendKeys(Keys.RETURN);
    }

    public void addProductTwoToBag() {
        scrollIntoView(ProductTwo);
        Click(ProductTwo);
        waitForElement(OneSize);
        Click(OneSize);
        Click(AddToBag);
    }

}
